os: linux
dist: bionic
language: node_js
node_js:
  - "10"
jobs:
  include:
    #- name: Lint
    #  script: npm run lint
    - name: Test
      script: npm test
    - name: Build & Deploy
      script: then npm run build
      before_deploy:
        - echo "Deploying!"
      deploy:
        - provider: script
          skip_cleanup: true
          on:
            branch: devfest2020
          script: firebase deploy --token "$FIREBASE_TOKEN"