os: linux
dist: bionic
language: node_js
node_js:
  - "10"
jobs:
  include:
    - name: Lint
      script: npm run lint
    - name: Test
      script: npm test
    - name: Build & Deploy
      script: if [ "$TRAVIS_BRANCH" == "master" ]; then npm run build; else BUILD_ENV=development npm run build; fi
      before_deploy:
        - echo "Deploying!"
      deploy:
        - provider: firebase
          skip_cleanup: true
          on:
            branch: devfest
          project: devfest-together-3f484
          token:
            secure: "TODO"