language: node_js
node_js:
- 12
cache: npm
jobs:
  include:
  - name: Build & Deploy
    script: if [ "$TRAVIS_BRANCH" == "master" ]; then npm run build; else BUILD_ENV=development npm run build; fi
    before_deploy:
    - echo "Deploying!"
    deploy:
    - provider: firebase
      skip_cleanup: true
      on:
        branch: devfest2020
      project: devfest2020-287916
      token:
        secure: Dvsh9QZIEVRewXV4ClNwr6NlHt0eDAcKYCY6xOjzpZcTF1PeXTbxUhR80QiIM8LCOJlwsxfw+ITybXKtm/J/KvPqddDYaprzarQfDpcCMiNJaXgXSqW1TTQXWFHDp3viRdd5AQ5VmjbGPcWzEwA2npS+lJ0R0aGjEuCeQ8Z8E++ISIIvBaMW6I97FaiL+TtgZJsy4vsxDucinoKKgknzRKt9h7wzUT5uReFW1VZ+BU8b9FvKzOXXa+KvDxApGX0ydkMzx/7MjDdEd2FpZjNLv62mPuWFb5Evn6DumGlAI8G9JZMi7SSpEhlFeJ3CTRtqEMeK7Snn78UHed//WMIGRISCYPNmnPAyyLWzpzJE/IslOSH0RrBPqQMA9ydarkCy6//56oTbTl9ACFGrAqiBRICsH9k2MLxeJ9Mr+P+MoPaie81nqTe4VKSWpN1zabt64pkTQoT9lSWyhFX7brosKJlVtU5o1aZAPc2s+XeScrefa6riaHZE7le4Xwwv8j3iPQhxj+l3iD5tFU1jcBspyJLu9EEoyEJjxJilVd7VNYp/OmQUCggSGlNVZFxeqzmLYedl/9Ob8pRTovovSqSnUYnFXFFHTny7Rfjv+ZqzYKl39on267a7zewNzA7M3SeszxjtrhOfAV6gowGxHxPn9CTnCW8SBCVWUlWjCj3xoJ8=

